### PR TITLE
Fail to `require('coffee-script')` when kernel launched by Hydrogen

### PR DESCRIPTION
**Pull request by slavaGanzin**
Hi Nicolas

When I'm using with hydrogen it requires coffee-script module from local project and not from jp-coffeescipt and not global one. 
Clearly I didn't like use jp-coffeescript dependency  - I think it would be frustrating if coffeescript updates globally and new feature wouldn't work in ipython.
But you choose

### CODE REVIEW

**Comment by slavaGanzin** [comment]
This PR doesn't work well.  I'll use global path until your advice

**Comment by n-riesco** [comment]
My understanding is that installation-order matters. If you run first:

```
$ sudo npm install -g coffee-script
```

when you install `jp-coffeescript`:

```
$ sudo npm install -g jp-coffeescript
```

 `npm` will detect coffee-script is already installed and it won't install it locally.

I think the problem you're seen is caused by how I've declared the coffee-script dependency in `package.json`:

```
"coffee-script": "latest",
```

I'm going to replace the dependency with:

```
"coffee-script": "<=1.0.0",
```

Please, let me know if this fixes your problem.

**Comment by slavaGanzin** [comment]
No it doens't help: It looks to NODE_PATH but it's unset at my machine as on many ones.
I think best way to do it:
npm link coffee-script in jp-coffee folder after npm install (it will cut local coffeescript and replace it with global one if it exists).
And find a way to get installation path of jp-coffee to require /path/to/jp-coffee/node_modules/coffee-script

**Comment by terraqout** [comment]
Nah, that isn't good too:
when I use a ipython console, i don't want to npm link to any folder when i'm working.

Ok, so NODE_PATH is appropriate?

**Comment by n-riesco** [comment]
I managed to mess up the dependency declaration. I wrote "<=1.0.0" instead of ">=1.0.0".

Could you try again? This time I've also published the update on `npm`.

**Comment by slavaGanzin** [comment]
No it does'nt create symlink to global coffee-script installation. 

Issue is in this code block:

``````
        var compiledCode = require('coffee-script').compile(code, {bare: true});
        if(DEBUG) { console.log("SM: COMPILED: ```\n", compiledCode, '\n'); }
        return vm.runInThisContext(compiledCode);
``````

When wm.runInThisContext it copy __dirname and __filename from original scope.
When you run it in console it assigns current folder to __dirname and /path/to/jp as it do in notebook mode.
Do node have some way to achieve path to executed file? Because when I use

```
in nel_server.js
        var path = require('path')
        var dir =  path.resolve(__dirname+'/node_modules/');
```

dir is equal to my project path and not jp-coffee itself

Maybe just pass path to nel_server when instantiating it in nel?

```
paths.server = path.join(paths.thisFolder, "nel_server.js");
```

**Comment by n-riesco** [comment]
I'm sorry but I don't understand what you're trying to achieve.

Could you provide me with instructions to reproduce the problem in my machine?

**Comment by slavaGanzin** [comment]
@n-riesco That's ok. 

You can just open atom with hydrogen at new project and run any code. I'm getting error "couldn't find coffee-script", while it's globally installed.
That's because vm search coffee-script in my project folder and not elsewhere.

**Comment by n-riesco** [comment]
OK, I got to reproduce the problem. An execution request to jp-coffeescript returns the error:

```
Error
Cannot find module 'coffee-script'
```

This error only happens within Atom. It fails even if `coffee-script` is installed under `jp-coffeescript/node_modules`.

The error doesn't happen if `coffee-script` is installed locally:

```
$ npm install coffee-script
```

**Comment by n-riesco** [comment]
@terraqout I've just committed a fix for this bug and published a new version on `npm`. Please, reopen this issue if it doesn't work for you.

**Comment by slavaGanzin** [comment]
God. I just loose that way to fix it. Thanks!

**Pull request closed without merging**
