### PR TITLE
--jp-install fix

### PR DESCRIPTION
**Pull request by slavaGanzin**

### CODE REVIEW

**Comment by n-riesco** [comment]
Thank you for the fix. Could you also add your name to the AUTHORS file? I ask contributors to add their name to express their consent for their contribution to be distributed under the [LICENSE](https://github.com/n-riesco/jp-coffeescript/blob/master/LICENSE) terms.

**Comment by slavaGanzin** [comment]
done

**Comment by n-riesco** [comment]
???? Did you close the PR by mistake?

**Comment by slavaGanzin** [comment]
yes

**Comment by n-riesco** [comment]
Then, I need you to resubmit the PR so that I can merge it.

**Comment by slavaGanzin** [comment]
done

**Comment by n-riesco** [comment]
Thanks!

**Pull request closed without merging**
